name: Build

env:
  DENO_DIR: ${{ github.workspace }}/deno_cache_directory

on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('example/deno.lock') }}
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x # Run with latest stable Deno.
      # Check if the code is formatted according to Deno's default
      # formatting conventions.
      - run: deno fmt --check --ignore=$DENO_DIR

      # Scan the code for syntax errors and style issues. If
      # you want to use a custom linter configuration you can add a configuration file with --config <myconfig>
      - run: deno lint --ignore=$DENO_DIR

      - run: deno task test
        working-directory: ./example
